# Generated by Django 5.2.12 on 2026-08-23 20:22

import django.db.models.deletion
import secrets
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0006_default_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500)),
                ('secret', models.CharField(default=secrets.token_urlsafe, help_text='Secret used to sign the payload via HMAC.', max_length=64)),
                ('events', models.JSONField(default=list, help_text="List of events this webhook subscribes to, e.g., ['hospital.status_changed', 'crisis.alert_created'].")),
                ('tenant_id', models.UUIDField(blank=True, help_text="If set, this webhook only receives events for this tenant's hospitals.", null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(blank=True, help_text='If set, this webhook only receives events for this hospital.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='hospitals.hospital')),
            ],
        ),
    ]
