# Generated by Django 5.2.12 on 2026-07-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='current_occupancy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='status',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=50),
        ),
        migrations.AddField(
            model_name='hospital',
            name='total_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
