# Generated by Django 5.2.12 on 2026-07-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_hospital_current_occupancy_hospital_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='status',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('MODERATE', 'Moderate'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=50),
        ),
    ]
