# Generated by Django 5.2.12 on 2026-08-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_alter_hospital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='current_occupancy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='department',
            name='total_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipment',
            name='quantity_available',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='equipment',
            name='quantity_in_use',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipment',
            name='quantity_maintenance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipment',
            name='quantity_total',
            field=models.IntegerField(default=1),
        ),
    ]
