# Generated by Django 5.2.12 on 2026-08-14 08:18

from django.db import migrations


def seed_default_tenant(apps, schema_editor):
    Tenant = apps.get_model('hospitals', 'Tenant')
    Hospital = apps.get_model('hospitals', 'Hospital')
    User = apps.get_model('accounts', 'User')

    if Hospital.objects.exists() or User.objects.exists():
        tenant, _ = Tenant.objects.get_or_create(name='Default Network')
        
        # Assign all existing hospitals to this tenant
        Hospital.objects.update(tenant=tenant)
        
        # Assign all operators and hospital_managers to this tenant
        User.objects.filter(role__in=['operator', 'hospital_manager']).update(tenant=tenant)

def reverse_seed(apps, schema_editor):
    # Nothing to do strictly, as fields will be dropped if migration is reversed
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_tenant_hospital_tenant'),
        ('accounts', '0004_user_push_token_user_tenant'),
    ]

    operations = [
        migrations.RunPython(seed_default_tenant, reverse_seed),
    ]

