# Generated by Django 5.2.12 on 2026-08-12 20:42

import pratiraksha.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='contact_phone',
            field=pratiraksha.fields.EncryptedCharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact',
            field=pratiraksha.fields.EncryptedCharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=pratiraksha.fields.EncryptedCharField(max_length=1000),
        ),
    ]
