# Generated by Django 5.2.12 on 2026-07-29 03:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('websocket', 'WebSocket')], max_length=20)),
                ('recipient', models.CharField(max_length=255)),
                ('hospital_id', models.UUIDField(blank=True, null=True)),
                ('trigger_event', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('stubbed', 'Stubbed')], default='queued', max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
