# Generated by Django 5.2.12 on 2026-08-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
