# Generated by Django 5.2.12 on 2026-08-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('websocket', 'WebSocket'), ('push', 'Push')], max_length=20),
        ),
    ]
